#!/usr/bin/env python3
"""
Mean Reversion Strategy for HFT Infrastructure Lab

Logic: when price deviates from its short-term moving average by more than
a threshold, bet on reversion to the mean.

- Price > SMA + threshold → SELL (overpriced, expect drop)
- Price < SMA - threshold → BUY  (underpriced, expect rise)
- Otherwise → HOLD

This is a simplified strategy to demonstrate the full pipeline:
  ITCH Feed → Parser → Strategy (signals) → OMS (risk checks) → P&L
"""
import time
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from collections import deque


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    timestamp_ns: int
    stock: str
    side: str          # 'BUY' or 'SELL'
    price: float
    quantity: int
    reason: str        # human-readable explanation


@dataclass
class StrategyStats:
    """Performance statistics for the strategy."""
    signals_generated: int = 0
    buys: int = 0
    sells: int = 0
    holds: int = 0
    total_latency_ns: int = 0

    @property
    def avg_latency_ns(self) -> float:
        if self.signals_generated == 0:
            return 0.0
        return self.total_latency_ns / self.signals_generated


class MeanReversionStrategy:
    """Simple mean reversion strategy using a rolling SMA.

    Args:
        window: Number of prices for the moving average (default: 20)
        threshold_pct: Deviation threshold as percentage (default: 0.1%)
        order_size: Default order quantity (default: 100 shares)
    """

    def __init__(self, window: int = 20, threshold_pct: float = 0.1,
                 order_size: int = 100) -> None:
        self.window = window
        self.threshold = threshold_pct / 100.0
        self.order_size = order_size

        # Per-stock price history
        self.prices: Dict[str, deque] = {}
        self.stats = StrategyStats()

    def _get_sma(self, stock: str) -> Optional[float]:
        """Calculate Simple Moving Average for a stock."""
        history = self.prices.get(stock)
        if not history or len(history) < self.window:
            return None
        return sum(history) / len(history)

    def on_market_data(self, stock: str, price: float,
                       timestamp_ns: int = 0) -> Optional[Signal]:
        """Process a price update and optionally generate a signal.

        Args:
            stock: Stock symbol
            price: Latest trade/quote price
            timestamp_ns: Message timestamp in nanoseconds
        Returns:
            Signal if action needed, None if HOLD
        """
        start = time.time_ns()

        # Update price history
        if stock not in self.prices:
            self.prices[stock] = deque(maxlen=self.window)
        self.prices[stock].append(price)

        # Need full window before generating signals
        sma = self._get_sma(stock)
        if sma is None:
            self.stats.holds += 1
            return None

        deviation = (price - sma) / sma
        signal = None

        if deviation > self.threshold:
            # Price above SMA + threshold → SELL (expect reversion down)
            signal = Signal(
                timestamp_ns=timestamp_ns,
                stock=stock,
                side='SELL',
                price=price,
                quantity=self.order_size,
                reason=f'price ${price:.2f} > SMA ${sma:.2f} (+{deviation*100:.3f}%)'
            )
            self.stats.sells += 1
            self.stats.signals_generated += 1

        elif deviation < -self.threshold:
            # Price below SMA - threshold → BUY (expect reversion up)
            signal = Signal(
                timestamp_ns=timestamp_ns,
                stock=stock,
                side='BUY',
                price=price,
                quantity=self.order_size,
                reason=f'price ${price:.2f} < SMA ${sma:.2f} ({deviation*100:.3f}%)'
            )
            self.stats.buys += 1
            self.stats.signals_generated += 1

        else:
            self.stats.holds += 1

        elapsed = time.time_ns() - start
        self.stats.total_latency_ns += elapsed
        return signal

    def print_stats(self) -> None:
        """Print strategy performance summary."""
        print(f"\n=== Strategy Statistics ===")
        print(f"  Signals: {self.stats.signals_generated} "
              f"({self.stats.buys} buys, {self.stats.sells} sells)")
        print(f"  Holds: {self.stats.holds}")
        total = self.stats.signals_generated + self.stats.holds
        if total > 0:
            signal_rate = self.stats.signals_generated / total * 100
            print(f"  Signal rate: {signal_rate:.1f}%")
        print(f"  Avg decision latency: {self.stats.avg_latency_ns:.0f} ns")


def demo() -> None:
    """Run standalone demo with synthetic price data."""
    import random

    print("=== Mean Reversion Strategy Demo ===\n")
    print("Window=20, Threshold=0.1%, Order size=100\n")

    strategy = MeanReversionStrategy(window=20, threshold_pct=0.1)
    rng = random.Random(42)

    # Simulate 200 price ticks for AAPL
    base_price = 175.00
    price = base_price

    signals: List[Signal] = []
    for i in range(200):
        # Random walk with mean reversion tendency
        price += rng.gauss(0, 0.15)
        ts = 34200_000_000_000 + i * 1_000_000_000  # 1 tick per second

        signal = strategy.on_market_data('AAPL', round(price, 2), ts)
        if signal:
            signals.append(signal)
            if len(signals) <= 10:
                print(f"  [{i:3d}] {signal.side:4s} AAPL @ ${signal.price:.2f} — {signal.reason}")

    if len(signals) > 10:
        print(f"  ... ({len(signals) - 10} more signals)")

    strategy.print_stats()

    # Show simulated P&L
    pnl = 0.0
    position = 0
    avg_entry = 0.0
    for sig in signals:
        if sig.side == 'BUY':
            avg_entry = ((avg_entry * position) + sig.price * sig.quantity) / (position + sig.quantity) if position > 0 else sig.price
            position += sig.quantity
        else:
            if position > 0:
                pnl += sig.quantity * (sig.price - avg_entry)
                position -= sig.quantity

    print(f"\n  Simulated P&L: ${pnl:,.2f}")
    print(f"  Final position: {position} shares")


if __name__ == '__main__':
    demo()
