/*
 * orderbook_pro_types.hpp — data model for FullOrderBook.
 *
 * Extracted from orderbook_pro.hpp: price-grid constants, enums (order types,
 * TIF, STP, statuses, events, reject reasons, session phases) and book PODs
 * (Order, PriceLevel, Trade, BookStats, BookEvent, TopOfBook, DepthLevel).
 *
 * These types are standalone — they depend on neither FullOrderBook nor BookCluster, so
 * consumers (strategies, risk, logger) can include just the model without pulling in
 * the whole matching engine.
 */
#pragma once

#include "../common/types.hpp"     // Side
#include <climits>                 // INT32_MAX (sentinel NO_ASK_TICKS)
#include <cstdint>

namespace orderbook_pro {

// Wire / model constants (could live in common/, but we want orderbook_pro
// to be standalone and not require modules other than common/types).
inline constexpr std::int32_t PRICE_MIN_TICKS = 0;            // lower edge of the grid
inline constexpr std::int32_t NO_BID_TICKS    = -1;           // sentinel "no quote"
inline constexpr std::int32_t NO_ASK_TICKS    = INT32_MAX;    // sentinel on the ask side


// Order type — DEC2025 NASDAQ + IEX taxonomies.
enum class OrderType : std::uint8_t {
    LIMIT       = 0,   // standard limit order
    IOC         = 1,   // Immediate-Or-Cancel: take what you can now, CANCEL the rest
    FOK         = 2,   // Fill-Or-Kill: full qty or nothing
    POST_ONLY   = 3,   // ALO — reject if you would become a taker (cross on entry)
    ICEBERG     = 4,   // show only `displayed_qty`, hide the rest
    STOP        = 5,   // trigger-on-price; after trigger becomes LIMIT/MARKET
    PEG         = 6,   // peg to mid or best bid/ask + offset
    MARKET      = 7,   // no price, you consume until exhausted
    HIDDEN      = 8,   // NOT shown in L1/L2 depth or trade tape (dark-pool semantics)
    AON         = 9,   // All-Or-None: fills like FOK but persists in the book (waits)
};


// Time in force.
enum class TimeInForce : std::uint8_t {
    DAY = 0,   // valid until end of session
    GTC = 1,   // Good-Till-Cancel — survives overnight rollover
    IOC = 2,   // Immediate-Or-Cancel (redundant with OrderType::IOC for convenience)
    FOK = 3,   // Fill-Or-Kill
    GTD = 4,   // Good-Til-Date — expire_ts_ns_ shows when
    GTX = 5,   // Good-Til-Cross — remainder cancelled after the next auction cross
};


// Self-trade prevention — what to do when our account ID hits our own quote.
enum class SelfTradePrevention : std::uint8_t {
    NONE              = 0,   // allow wash trade (usually FORBIDDEN, but for tests)
    CANCEL_NEWEST     = 1,   // incoming order cancelled
    CANCEL_OLDEST     = 2,   // resting order cancelled
    CANCEL_BOTH       = 3,   // both cancelled
    DECREMENT_AND_CXL = 4,   // decrement the smaller qty from both (NASDAQ DAC)
};


// Status of a single Order in its lifecycle.
enum class OrderStatus : std::uint8_t {
    NEW              = 0,   // accepted, not yet in the book (queue join in progress)
    OPEN             = 1,   // in the book, waiting for execution
    PARTIALLY_FILLED = 2,   // partially filled, remainder waiting
    FILLED           = 3,   // completely filled
    CANCELLED        = 4,   // cancelled by the user
    REJECTED         = 5,   // rejected before entry (locked/crossed/POST_ONLY cross)
    EXPIRED          = 6,   // GTD/DAY/IOC/FOK expired
    REPLACED         = 7,   // cancel+resubmit via modify()
};


// Type of event generated by the book (OnEvent callback).
enum class EventType : std::uint8_t {
    ACCEPT       = 0,   // order accepted into the book (NEW → OPEN)
    REJECT       = 1,   // rejected before being added
    FILL         = 2,   // execution (may be partial or full)
    CANCEL       = 3,   // user cancel
    EXPIRE       = 4,   // expire (GTD/DAY)
    REPLACE      = 5,   // modify success
    BOOK_UPDATE  = 6,   // book changed (top of book / depth)
};


// Reason code for REJECT — so the caller knows why the order was rejected.
enum class RejectReason : std::uint8_t {
    NONE                  = 0,
    PRICE_OUT_OF_RANGE    = 1,   // price < 0 or price >= LEVELS
    QTY_ZERO_OR_NEGATIVE  = 2,
    POOL_EXHAUSTED        = 3,   // no room in the order pool
    POST_ONLY_WOULD_CROSS = 4,   // POST_ONLY but the order crosses the market
    FOK_NOT_FILLABLE      = 5,   // FOK and insufficient liquidity
    SELF_TRADE_BLOCKED    = 6,   // STP triggered
    DUPLICATE_ID          = 7,   // ID already exists in the book
    LOCKED_MARKET         = 8,   // bid == ask (cross protection)
    CROSSED_MARKET        = 9,   // bid > ask (crossed market)
    HALTED                = 10,  // book halted (trading halt)
    MIN_QTY_NOT_MET       = 11,  // matched < min_qty constraint
    LULD_BAND_BREACH      = 12,  // price outside Limit Up / Limit Down bands
    SSR_RESTRICTED        = 13,  // short sale with active SSR ≤ best bid (Rule 201)
    REDUCE_ONLY_NO_POSITION = 14, // reduce-only with no position to reduce
    RATE_LIMITED          = 15,  // account exceeded the token bucket (msg rate)
    MARKET_CLOSED         = 16,  // session in CLOSED phase — submits rejected
    MMP_TRIPPED           = 17,  // market maker protection active — quotes blocked until reset
};


// Exchange session phase. The book starts in CONTINUOUS (backward compat) —
// you opt into the lifecycle via begin_pre_open()/open_market()/...
enum class SessionPhase : std::uint8_t {
    PRE_OPEN   = 0,   // orders queue for the opening cross, no continuous match
    CONTINUOUS = 1,   // normal matching
    CLOSING    = 2,   // orders queue for the closing cross
    CLOSED     = 3,   // submits rejected (MARKET_CLOSED); cancel allowed
};


// A single order in the book — POD, cache-aligned (one 64 B line).
//
// Intrusive linked list: each Order holds next_at_level_/prev_at_level_
// within its PriceLevel. Cancel = O(1) unlink without search.
struct alignas(64) Order {
    std::uint64_t  id;                  // unique order_id (caller-provided or auto)
    std::uint64_t  client_id;            // client ID (for STP)
    std::int32_t   price_ticks;          // price in ticks
    std::int32_t   total_qty;            // total order qty
    std::int32_t   filled_qty;           // how much filled so far
    std::int32_t   displayed_qty;        // for ICEBERG: how much is visible; LIMIT: == total
    Side           side;                 // BUY / SELL
    OrderType      type;                 // order type
    TimeInForce    tif;                  // time in force
    OrderStatus    status;               // current state
    std::uint64_t  submit_ts_ns;         // monotonic timestamp of entry into the book
    std::uint64_t  expire_ts_ns;         // for GTD; 0 = never
    std::int32_t   stop_trigger_ticks;   // for STOP/PEG: trigger price / peg base
    std::int32_t   peg_offset_ticks;     // for PEG: offset from best bid/ask/mid
    std::int32_t   peg_cap_ticks;        // for PEG: limit cap (BUY: max, SELL: min); 0 = none
    std::int32_t   decision_mid_ticks;   // mid snapshot at submit — for IS (Implementation Shortfall)
    std::int32_t   iceberg_display_size; // for ICEBERG: refresh size (0 = not an iceberg)
    std::uint64_t  first_fill_ts_ns;     // ts of first fill (0 if nothing filled)
    Order*         next_at_level;        // intrusive list (FIFO)
    Order*         prev_at_level;
    Order*         next_free;            // free list in the pool (when the slot is free)

    void reset() noexcept {
        id = 0;
        client_id = 0;
        price_ticks = 0;
        total_qty = 0;
        filled_qty = 0;
        displayed_qty = 0;
        side = Side::BUY;
        type = OrderType::LIMIT;
        tif  = TimeInForce::DAY;
        status = OrderStatus::NEW;
        submit_ts_ns = 0;
        expire_ts_ns = 0;
        stop_trigger_ticks = 0;
        peg_offset_ticks = 0;
        peg_cap_ticks = 0;
        decision_mid_ticks = -1;
        iceberg_display_size = 0;
        first_fill_ts_ns = 0;
        next_at_level = nullptr;
        prev_at_level = nullptr;
        next_free = nullptr;
    }

    std::int32_t remaining_qty() const noexcept { return total_qty - filled_qty; }
    bool is_active() const noexcept {
        return status == OrderStatus::OPEN || status == OrderStatus::PARTIALLY_FILLED;
    }
};


// A single price level: head/tail FIFO + aggregates for L2.
struct alignas(64) PriceLevel {
    Order*        head            = nullptr;   // first in the queue (earliest scheduled)
    Order*        tail            = nullptr;   // last (most recent join)
    std::int32_t  total_qty       = 0;          // Σ displayed_qty (visible liquidity)
    std::int32_t  total_hidden    = 0;          // Σ ICEBERG hidden (invisible)
    std::int32_t  order_count     = 0;          // how many orders in the queue (for queue position)

    bool empty() const noexcept { return head == nullptr; }
    void clear() noexcept {
        head = tail = nullptr;
        total_qty = total_hidden = 0;
        order_count = 0;
    }
};


// A single execution on the trade tape.
struct alignas(32) Trade {
    std::uint64_t  exec_id;          // unique execution ID (monotonic)
    std::uint64_t  maker_order_id;
    std::uint64_t  taker_order_id;
    std::int32_t   price_ticks;
    std::int32_t   qty;
    Side           taker_side;       // which side was the aggressor
    std::uint64_t  ts_ns;
};


// Snapshot of book stats (informational, lazy).
struct BookStats {
    std::uint64_t  total_orders_added       = 0;
    std::uint64_t  total_orders_cancelled   = 0;
    std::uint64_t  total_orders_replaced    = 0;
    std::uint64_t  total_orders_rejected    = 0;
    std::uint64_t  total_orders_expired     = 0;
    std::uint64_t  total_fills              = 0;
    std::uint64_t  total_volume             = 0;     // Σ qty of all fills
    std::uint64_t  total_locked_rejects     = 0;
    std::uint64_t  total_self_trade_blocks  = 0;
    std::uint64_t  peak_order_pool_used     = 0;
    std::uint64_t  total_stop_triggers      = 0;
    std::uint64_t  total_peg_reprices       = 0;
    std::uint64_t  total_mass_cancels       = 0;
    std::uint64_t  total_auctions_executed  = 0;
    std::uint64_t  total_mass_quotes        = 0;
    std::uint64_t  total_tob_changes        = 0;
    std::uint64_t  total_sweeps             = 0;          // taker fills (regardless of levels)
    std::uint64_t  multi_level_sweeps       = 0;          // taker matched >= 2 price levels
    std::uint64_t  sum_levels_touched       = 0;          // Σ levels traversed (per sweep)
    std::uint64_t  priority_preserved_mods  = 0;          // modify qty-DOWN same-price
    std::uint64_t  priority_lost_mods       = 0;          // modify changing price / qty UP
    std::uint64_t  total_quoted_spread_ticks_obs = 0;     // Σ best_ask-best_bid at observation time
    std::uint64_t  total_quoted_spread_samples   = 0;     // number of samples (for mean spread)
    std::uint64_t  total_effective_spread_2x_ticks = 0;   // Σ 2×|fill_px - mid| (signed)
    std::uint64_t  total_effective_spread_samples  = 0;   // number of fills (for mean effective)
};


// Event passed to the callback.
struct BookEvent {
    EventType     type;
    std::uint64_t order_id;          // for ACCEPT/REJECT/CANCEL/EXPIRE/REPLACE/FILL
    std::uint64_t maker_id;          // for FILL: maker side
    std::int32_t  price_ticks;
    std::int32_t  qty;               // for FILL: how much, for CANCEL: remaining qty
    OrderStatus   resulting_status;
    RejectReason  reject_reason;     // only for REJECT
    std::uint64_t ts_ns;
    std::uint64_t seq_num = 0;       // monotonic — consumer dedup / gap detect
    std::uint64_t client_id = 0;     // account (0 = unknown/anonymous) — drop copy
};


// Top-of-book quote — the structure most often consumed by strategies.
struct TopOfBook {
    std::int32_t  best_bid_ticks;
    std::int32_t  best_ask_ticks;
    std::int32_t  bid_qty;            // displayed at best bid
    std::int32_t  ask_qty;            // displayed at best ask
    std::int32_t  bid_count;          // how many orders at best bid
    std::int32_t  ask_count;
};


// L2 depth row.
struct DepthLevel {
    std::int32_t  price_ticks;
    std::int32_t  qty;
    std::int32_t  order_count;
};

}  // namespace orderbook_pro
